package com.shop.user.entity;

public class Money {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_money.id
     *
     * @mbg.generated Sun May 17 13:59:07 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_money.money
     *
     * @mbg.generated Sun May 17 13:59:07 CST 2020
     */
    private Integer money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_money.id
     *
     * @return the value of tb_money.id
     *
     * @mbg.generated Sun May 17 13:59:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_money.id
     *
     * @param id the value for tb_money.id
     *
     * @mbg.generated Sun May 17 13:59:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_money.money
     *
     * @return the value of tb_money.money
     *
     * @mbg.generated Sun May 17 13:59:07 CST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_money.money
     *
     * @param money the value for tb_money.money
     *
     * @mbg.generated Sun May 17 13:59:07 CST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}