package com.shop.orders.entity;

public class Buyermoney {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyerMoney.id
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyerMoney.money
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    private Integer money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyerMoney.id
     *
     * @return the value of buyerMoney.id
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyerMoney.id
     *
     * @param id the value for buyerMoney.id
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyerMoney.money
     *
     * @return the value of buyerMoney.money
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyerMoney.money
     *
     * @param money the value for buyerMoney.money
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}