package com.shop.goods.mapper;

import com.shop.goods.entity.GoodsDescribe;
import com.shop.goods.entity.GoodsDescribeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsDescribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    int countByExample(GoodsDescribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    int deleteByExample(GoodsDescribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    int insert(GoodsDescribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    int insertSelective(GoodsDescribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    List<GoodsDescribe> selectByExample(GoodsDescribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    GoodsDescribe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") GoodsDescribe record, @Param("example") GoodsDescribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    int updateByExample(@Param("record") GoodsDescribe record, @Param("example") GoodsDescribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    int updateByPrimaryKeySelective(GoodsDescribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    int updateByPrimaryKey(GoodsDescribe record);
}