package com.shop.phone.mapper;

import com.shop.phone.entity.PhoneTransaction;
import com.shop.phone.entity.PhoneTransactionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhoneTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneTransaction
     *
     * @mbggenerated Fri May 08 16:35:02 CST 2020
     */
    int countByExample(PhoneTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneTransaction
     *
     * @mbggenerated Fri May 08 16:35:02 CST 2020
     */
    int deleteByExample(PhoneTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneTransaction
     *
     * @mbggenerated Fri May 08 16:35:02 CST 2020
     */
    int deleteByPrimaryKey(Integer ordersid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneTransaction
     *
     * @mbggenerated Fri May 08 16:35:02 CST 2020
     */
    int insert(PhoneTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneTransaction
     *
     * @mbggenerated Fri May 08 16:35:02 CST 2020
     */
    int insertSelective(PhoneTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneTransaction
     *
     * @mbggenerated Fri May 08 16:35:02 CST 2020
     */
    List<PhoneTransaction> selectByExample(PhoneTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneTransaction
     *
     * @mbggenerated Fri May 08 16:35:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") PhoneTransaction record, @Param("example") PhoneTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneTransaction
     *
     * @mbggenerated Fri May 08 16:35:02 CST 2020
     */
    int updateByExample(@Param("record") PhoneTransaction record, @Param("example") PhoneTransactionExample example);
}