package com.shop.email.entity;

public class EmailTransaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emailTransaction.ordersId
     *
     * @mbggenerated Fri May 08 13:43:28 CST 2020
     */
    private Integer ordersid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emailTransaction.ordersId
     *
     * @return the value of emailTransaction.ordersId
     *
     * @mbggenerated Fri May 08 13:43:28 CST 2020
     */
    public Integer getOrdersid() {
        return ordersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emailTransaction.ordersId
     *
     * @param ordersid the value for emailTransaction.ordersId
     *
     * @mbggenerated Fri May 08 13:43:28 CST 2020
     */
    public void setOrdersid(Integer ordersid) {
        this.ordersid = ordersid;
    }
}