package com.shop.orders.mapper;

import com.shop.orders.entity.Buyermoney;
import com.shop.orders.entity.BuyermoneyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyermoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyerMoney
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int countByExample(BuyermoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyerMoney
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int deleteByExample(BuyermoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyerMoney
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyerMoney
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int insert(Buyermoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyerMoney
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int insertSelective(Buyermoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyerMoney
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    List<Buyermoney> selectByExample(BuyermoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyerMoney
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    Buyermoney selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyerMoney
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") Buyermoney record, @Param("example") BuyermoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyerMoney
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int updateByExample(@Param("record") Buyermoney record, @Param("example") BuyermoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyerMoney
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int updateByPrimaryKeySelective(Buyermoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyerMoney
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int updateByPrimaryKey(Buyermoney record);
}