package com.shop.orders.mapper;

import com.shop.orders.entity.Goodscounts;
import com.shop.orders.entity.GoodscountsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodscountsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCounts
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int countByExample(GoodscountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCounts
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int deleteByExample(GoodscountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCounts
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCounts
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int insert(Goodscounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCounts
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int insertSelective(Goodscounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCounts
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    List<Goodscounts> selectByExample(GoodscountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCounts
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    Goodscounts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCounts
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") Goodscounts record, @Param("example") GoodscountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCounts
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int updateByExample(@Param("record") Goodscounts record, @Param("example") GoodscountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCounts
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int updateByPrimaryKeySelective(Goodscounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCounts
     *
     * @mbggenerated Wed May 06 00:05:41 CST 2020
     */
    int updateByPrimaryKey(Goodscounts record);
}