package com.shop.goods.entity;

public class GoodsDescribe {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsDescribe.id
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsDescribe.goodsId
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsDescribe.URL
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsDescribe.describe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsDescribe.id
     *
     * @return the value of goodsDescribe.id
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsDescribe.id
     *
     * @param id the value for goodsDescribe.id
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsDescribe.goodsId
     *
     * @return the value of goodsDescribe.goodsId
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsDescribe.goodsId
     *
     * @param goodsid the value for goodsDescribe.goodsId
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsDescribe.URL
     *
     * @return the value of goodsDescribe.URL
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsDescribe.URL
     *
     * @param url the value for goodsDescribe.URL
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsDescribe.describe
     *
     * @return the value of goodsDescribe.describe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsDescribe.describe
     *
     * @param describe the value for goodsDescribe.describe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public void setDescribe(String describe) {
        this.describe = describe;
    }
}