package com.shop.goods.entity;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sellerId
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    private Integer sellerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.category
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.salevol
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    private Integer salevol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.mainURL
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    private String mainurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.mainDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    private String maindescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sellerId
     *
     * @return the value of goods.sellerId
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public Integer getSellerid() {
        return sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sellerId
     *
     * @param sellerid the value for goods.sellerId
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public void setSellerid(Integer sellerid) {
        this.sellerid = sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.category
     *
     * @return the value of goods.category
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.category
     *
     * @param category the value for goods.category
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.salevol
     *
     * @return the value of goods.salevol
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public Integer getSalevol() {
        return salevol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.salevol
     *
     * @param salevol the value for goods.salevol
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public void setSalevol(Integer salevol) {
        this.salevol = salevol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.mainURL
     *
     * @return the value of goods.mainURL
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public String getMainurl() {
        return mainurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.mainURL
     *
     * @param mainurl the value for goods.mainURL
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public void setMainurl(String mainurl) {
        this.mainurl = mainurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.mainDescribe
     *
     * @return the value of goods.mainDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public String getMaindescribe() {
        return maindescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.mainDescribe
     *
     * @param maindescribe the value for goods.mainDescribe
     *
     * @mbggenerated Fri May 08 21:29:16 CST 2020
     */
    public void setMaindescribe(String maindescribe) {
        this.maindescribe = maindescribe;
    }
}