package com.shop.goods.entity;

public class Goodscounts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsCounts.id
     *
     * @mbggenerated Tue May 05 23:54:52 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsCounts.counts
     *
     * @mbggenerated Tue May 05 23:54:52 CST 2020
     */
    private Integer counts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsCounts.id
     *
     * @return the value of goodsCounts.id
     *
     * @mbggenerated Tue May 05 23:54:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsCounts.id
     *
     * @param id the value for goodsCounts.id
     *
     * @mbggenerated Tue May 05 23:54:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsCounts.counts
     *
     * @return the value of goodsCounts.counts
     *
     * @mbggenerated Tue May 05 23:54:52 CST 2020
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsCounts.counts
     *
     * @param counts the value for goodsCounts.counts
     *
     * @mbggenerated Tue May 05 23:54:52 CST 2020
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }
}