package com.shop.authority.mapper;

import com.shop.authority.entity.Url;
import com.shop.authority.entity.UrlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    int countByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    int deleteByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    int insert(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    int insertSelective(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    List<Url> selectByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    Url selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") Url record, @Param("example") UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    int updateByExample(@Param("record") Url record, @Param("example") UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    int updateByPrimaryKeySelective(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    int updateByPrimaryKey(Url record);
}