package com.shop.email.mapper;

import com.shop.email.entity.EmailTransaction;
import com.shop.email.entity.EmailTransactionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emailTransaction
     *
     * @mbggenerated Fri May 08 13:43:28 CST 2020
     */
    int countByExample(EmailTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emailTransaction
     *
     * @mbggenerated Fri May 08 13:43:28 CST 2020
     */
    int deleteByExample(EmailTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emailTransaction
     *
     * @mbggenerated Fri May 08 13:43:28 CST 2020
     */
    int deleteByPrimaryKey(Integer ordersid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emailTransaction
     *
     * @mbggenerated Fri May 08 13:43:28 CST 2020
     */
    int insert(EmailTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emailTransaction
     *
     * @mbggenerated Fri May 08 13:43:28 CST 2020
     */
    int insertSelective(EmailTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emailTransaction
     *
     * @mbggenerated Fri May 08 13:43:28 CST 2020
     */
    List<EmailTransaction> selectByExample(EmailTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emailTransaction
     *
     * @mbggenerated Fri May 08 13:43:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") EmailTransaction record, @Param("example") EmailTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emailTransaction
     *
     * @mbggenerated Fri May 08 13:43:28 CST 2020
     */
    int updateByExample(@Param("record") EmailTransaction record, @Param("example") EmailTransactionExample example);
}