package com.example.onlineshop.entity;

public class Comments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.buyerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer buyerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.goodsId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comments
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.commentsId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer commentsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.buyerId
     *
     * @return the value of comments.buyerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getBuyerid() {
        return buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.buyerId
     *
     * @param buyerid the value for comments.buyerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setBuyerid(Integer buyerid) {
        this.buyerid = buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.goodsId
     *
     * @return the value of comments.goodsId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.goodsId
     *
     * @param goodsid the value for comments.goodsId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comments
     *
     * @return the value of comments.comments
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comments
     *
     * @param comments the value for comments.comments
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.commentsId
     *
     * @return the value of comments.commentsId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getCommentsid() {
        return commentsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.commentsId
     *
     * @param commentsid the value for comments.commentsId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setCommentsid(Integer commentsid) {
        this.commentsid = commentsid;
    }
}