package com.example.onlineshop.entity;

public class Coupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.couponId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer couponid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.buyerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer buyerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.couponWarehouseId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer couponwarehouseid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.couponId
     *
     * @return the value of coupon.couponId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getCouponid() {
        return couponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.couponId
     *
     * @param couponid the value for coupon.couponId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setCouponid(Integer couponid) {
        this.couponid = couponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.buyerId
     *
     * @return the value of coupon.buyerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getBuyerid() {
        return buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.buyerId
     *
     * @param buyerid the value for coupon.buyerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setBuyerid(Integer buyerid) {
        this.buyerid = buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.couponWarehouseId
     *
     * @return the value of coupon.couponWarehouseId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getCouponwarehouseid() {
        return couponwarehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.couponWarehouseId
     *
     * @param couponwarehouseid the value for coupon.couponWarehouseId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setCouponwarehouseid(Integer couponwarehouseid) {
        this.couponwarehouseid = couponwarehouseid;
    }
}