package com.example.onlineshop.entity;

public class Favourite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourite.buyerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer buyerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favourite.goodsId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer goodsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourite.buyerId
     *
     * @return the value of favourite.buyerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getBuyerid() {
        return buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourite.buyerId
     *
     * @param buyerid the value for favourite.buyerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setBuyerid(Integer buyerid) {
        this.buyerid = buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favourite.goodsId
     *
     * @return the value of favourite.goodsId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favourite.goodsId
     *
     * @param goodsid the value for favourite.goodsId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }
}