package com.example.onlineshop.entity;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sellerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer sellerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.category
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.salevol
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer salevol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.count
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.desc
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sellerId
     *
     * @return the value of goods.sellerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getSellerid() {
        return sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sellerId
     *
     * @param sellerid the value for goods.sellerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setSellerid(Integer sellerid) {
        this.sellerid = sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.category
     *
     * @return the value of goods.category
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.category
     *
     * @param category the value for goods.category
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.salevol
     *
     * @return the value of goods.salevol
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getSalevol() {
        return salevol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.salevol
     *
     * @param salevol the value for goods.salevol
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setSalevol(Integer salevol) {
        this.salevol = salevol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.count
     *
     * @return the value of goods.count
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.count
     *
     * @param count the value for goods.count
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.desc
     *
     * @return the value of goods.desc
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.desc
     *
     * @param desc the value for goods.desc
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}