package com.example.onlineshop.entity;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buyerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer buyerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goodsId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.addressid
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer addressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.counts
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private Integer counts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.state
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.buyerId
     *
     * @return the value of order.buyerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getBuyerid() {
        return buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.buyerId
     *
     * @param buyerid the value for order.buyerId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setBuyerid(Integer buyerid) {
        this.buyerid = buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goodsId
     *
     * @return the value of order.goodsId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goodsId
     *
     * @param goodsid the value for order.goodsId
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.addressid
     *
     * @return the value of order.addressid
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.addressid
     *
     * @param addressid the value for order.addressid
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.counts
     *
     * @return the value of order.counts
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.counts
     *
     * @param counts the value for order.counts
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.state
     *
     * @return the value of order.state
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.state
     *
     * @param state the value for order.state
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    public void setState(String state) {
        this.state = state;
    }
}