package com.example.onlineshop.mapper;

import com.example.onlineshop.entity.Couponwarehouse;
import com.example.onlineshop.entity.CouponwarehouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CouponwarehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponWarehouse
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int countByExample(CouponwarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponWarehouse
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int deleteByExample(CouponwarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponWarehouse
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponWarehouse
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int insert(Couponwarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponWarehouse
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int insertSelective(Couponwarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponWarehouse
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    List<Couponwarehouse> selectByExample(CouponwarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponWarehouse
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    Couponwarehouse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponWarehouse
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") Couponwarehouse record, @Param("example") CouponwarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponWarehouse
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int updateByExample(@Param("record") Couponwarehouse record, @Param("example") CouponwarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponWarehouse
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int updateByPrimaryKeySelective(Couponwarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table couponWarehouse
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int updateByPrimaryKey(Couponwarehouse record);
}