package com.example.onlineshop.mapper;

import com.example.onlineshop.entity.Shoppingcart;
import com.example.onlineshop.entity.ShoppingcartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShoppingcartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingCart
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int countByExample(ShoppingcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingCart
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int deleteByExample(ShoppingcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingCart
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int insert(Shoppingcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingCart
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int insertSelective(Shoppingcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingCart
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    List<Shoppingcart> selectByExample(ShoppingcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingCart
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") Shoppingcart record, @Param("example") ShoppingcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingCart
     *
     * @mbggenerated Sat May 02 15:06:53 CST 2020
     */
    int updateByExample(@Param("record") Shoppingcart record, @Param("example") ShoppingcartExample example);
}