package com.shop.gateway.entity;

public class RoleUrl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_url.id
     *
     * @mbggenerated Thu May 14 13:32:17 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_url.global_id
     *
     * @mbggenerated Thu May 14 13:32:17 CST 2020
     */
    private Long globalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_url.role_id
     *
     * @mbggenerated Thu May 14 13:32:17 CST 2020
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_url.url_id
     *
     * @mbggenerated Thu May 14 13:32:17 CST 2020
     */
    private Integer urlId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_url.id
     *
     * @return the value of tb_role_url.id
     *
     * @mbggenerated Thu May 14 13:32:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_url.id
     *
     * @param id the value for tb_role_url.id
     *
     * @mbggenerated Thu May 14 13:32:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_url.global_id
     *
     * @return the value of tb_role_url.global_id
     *
     * @mbggenerated Thu May 14 13:32:17 CST 2020
     */
    public Long getGlobalId() {
        return globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_url.global_id
     *
     * @param globalId the value for tb_role_url.global_id
     *
     * @mbggenerated Thu May 14 13:32:17 CST 2020
     */
    public void setGlobalId(Long globalId) {
        this.globalId = globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_url.role_id
     *
     * @return the value of tb_role_url.role_id
     *
     * @mbggenerated Thu May 14 13:32:17 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_url.role_id
     *
     * @param roleId the value for tb_role_url.role_id
     *
     * @mbggenerated Thu May 14 13:32:17 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_url.url_id
     *
     * @return the value of tb_role_url.url_id
     *
     * @mbggenerated Thu May 14 13:32:17 CST 2020
     */
    public Integer getUrlId() {
        return urlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_url.url_id
     *
     * @param urlId the value for tb_role_url.url_id
     *
     * @mbggenerated Thu May 14 13:32:17 CST 2020
     */
    public void setUrlId(Integer urlId) {
        this.urlId = urlId;
    }
}