package com.shop.user.mapper;

import com.shop.user.entity.Money;
import com.shop.user.entity.MoneyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_money
     *
     * @mbg.generated Tue May 12 21:40:38 CST 2020
     */
    long countByExample(MoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_money
     *
     * @mbg.generated Tue May 12 21:40:38 CST 2020
     */
    int deleteByExample(MoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_money
     *
     * @mbg.generated Tue May 12 21:40:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_money
     *
     * @mbg.generated Tue May 12 21:40:38 CST 2020
     */
    int insert(Money record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_money
     *
     * @mbg.generated Tue May 12 21:40:38 CST 2020
     */
    int insertSelective(Money record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_money
     *
     * @mbg.generated Tue May 12 21:40:38 CST 2020
     */
    List<Money> selectByExample(MoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_money
     *
     * @mbg.generated Tue May 12 21:40:38 CST 2020
     */
    Money selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_money
     *
     * @mbg.generated Tue May 12 21:40:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Money record, @Param("example") MoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_money
     *
     * @mbg.generated Tue May 12 21:40:38 CST 2020
     */
    int updateByExample(@Param("record") Money record, @Param("example") MoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_money
     *
     * @mbg.generated Tue May 12 21:40:38 CST 2020
     */
    int updateByPrimaryKeySelective(Money record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_money
     *
     * @mbg.generated Tue May 12 21:40:38 CST 2020
     */
    int updateByPrimaryKey(Money record);
}