package com.shop.authority.entity;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.id
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.gloabl_id
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    private Long gloablId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.name
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.id
     *
     * @return the value of tb_role.id
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.id
     *
     * @param id the value for tb_role.id
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.gloabl_id
     *
     * @return the value of tb_role.gloabl_id
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public Long getGloablId() {
        return gloablId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.gloabl_id
     *
     * @param gloablId the value for tb_role.gloabl_id
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public void setGloablId(Long gloablId) {
        this.gloablId = gloablId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.name
     *
     * @return the value of tb_role.name
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.name
     *
     * @param name the value for tb_role.name
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}