package com.shop.authority.entity;

public class Url {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_url.id
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_url.global_id
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    private Long globalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_url.url_pre
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    private String urlPre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_url.describe
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_url.id
     *
     * @return the value of tb_url.id
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_url.id
     *
     * @param id the value for tb_url.id
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_url.global_id
     *
     * @return the value of tb_url.global_id
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public Long getGlobalId() {
        return globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_url.global_id
     *
     * @param globalId the value for tb_url.global_id
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public void setGlobalId(Long globalId) {
        this.globalId = globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_url.url_pre
     *
     * @return the value of tb_url.url_pre
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public String getUrlPre() {
        return urlPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_url.url_pre
     *
     * @param urlPre the value for tb_url.url_pre
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public void setUrlPre(String urlPre) {
        this.urlPre = urlPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_url.describe
     *
     * @return the value of tb_url.describe
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_url.describe
     *
     * @param describe the value for tb_url.describe
     *
     * @mbggenerated Fri May 15 17:20:54 CST 2020
     */
    public void setDescribe(String describe) {
        this.describe = describe;
    }
}