package com.shop.seller.mapper;

import com.shop.seller.entity.Sellermoney;
import com.shop.seller.entity.SellermoneyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SellermoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerMoney
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    int countByExample(SellermoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerMoney
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    int deleteByExample(SellermoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerMoney
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerMoney
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    int insert(Sellermoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerMoney
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    int insertSelective(Sellermoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerMoney
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    List<Sellermoney> selectByExample(SellermoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerMoney
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    Sellermoney selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerMoney
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") Sellermoney record, @Param("example") SellermoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerMoney
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    int updateByExample(@Param("record") Sellermoney record, @Param("example") SellermoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerMoney
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    int updateByPrimaryKeySelective(Sellermoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sellerMoney
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    int updateByPrimaryKey(Sellermoney record);
}