package com.shop.seller.entity;

public class Sellermoney {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sellerMoney.id
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sellerMoney.money
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    private Integer money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sellerMoney.id
     *
     * @return the value of sellerMoney.id
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sellerMoney.id
     *
     * @param id the value for sellerMoney.id
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sellerMoney.money
     *
     * @return the value of sellerMoney.money
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sellerMoney.money
     *
     * @param money the value for sellerMoney.money
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}