package com.shop.seller.entity;

public class Seller {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.id
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.password
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    private Integer password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.name
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.rate
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    private String rate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.id
     *
     * @return the value of seller.id
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.id
     *
     * @param id the value for seller.id
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.password
     *
     * @return the value of seller.password
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    public Integer getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.password
     *
     * @param password the value for seller.password
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    public void setPassword(Integer password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.name
     *
     * @return the value of seller.name
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.name
     *
     * @param name the value for seller.name
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.rate
     *
     * @return the value of seller.rate
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.rate
     *
     * @param rate the value for seller.rate
     *
     * @mbggenerated Tue May 05 19:47:12 CST 2020
     */
    public void setRate(String rate) {
        this.rate = rate;
    }
}