package com.shop.integral.entity;

public class BuyerIntegral {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyerIntegral.buyerId
     *
     * @mbggenerated Fri May 08 17:02:09 CST 2020
     */
    private Integer buyerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyerIntegral.integral
     *
     * @mbggenerated Fri May 08 17:02:09 CST 2020
     */
    private Integer integral;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyerIntegral.buyerId
     *
     * @return the value of buyerIntegral.buyerId
     *
     * @mbggenerated Fri May 08 17:02:09 CST 2020
     */
    public Integer getBuyerid() {
        return buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyerIntegral.buyerId
     *
     * @param buyerid the value for buyerIntegral.buyerId
     *
     * @mbggenerated Fri May 08 17:02:09 CST 2020
     */
    public void setBuyerid(Integer buyerid) {
        this.buyerid = buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyerIntegral.integral
     *
     * @return the value of buyerIntegral.integral
     *
     * @mbggenerated Fri May 08 17:02:09 CST 2020
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyerIntegral.integral
     *
     * @param integral the value for buyerIntegral.integral
     *
     * @mbggenerated Fri May 08 17:02:09 CST 2020
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }
}