package com.shop.integral.entity;

public class IntegralTransaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integralTransaction.ordersId
     *
     * @mbggenerated Fri May 08 17:02:09 CST 2020
     */
    private Integer ordersid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integralTransaction.ordersId
     *
     * @return the value of integralTransaction.ordersId
     *
     * @mbggenerated Fri May 08 17:02:09 CST 2020
     */
    public Integer getOrdersid() {
        return ordersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integralTransaction.ordersId
     *
     * @param ordersid the value for integralTransaction.ordersId
     *
     * @mbggenerated Fri May 08 17:02:09 CST 2020
     */
    public void setOrdersid(Integer ordersid) {
        this.ordersid = ordersid;
    }
}