package com.shop.buyer.mapper;

import com.shop.buyer.entity.Buyer;
import com.shop.buyer.entity.BuyerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated Fri May 08 12:54:33 CST 2020
     */
    int countByExample(BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated Fri May 08 12:54:33 CST 2020
     */
    int deleteByExample(BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated Fri May 08 12:54:33 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated Fri May 08 12:54:33 CST 2020
     */
    int insert(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated Fri May 08 12:54:33 CST 2020
     */
    int insertSelective(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated Fri May 08 12:54:33 CST 2020
     */
    List<Buyer> selectByExample(BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated Fri May 08 12:54:33 CST 2020
     */
    Buyer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated Fri May 08 12:54:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") Buyer record, @Param("example") BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated Fri May 08 12:54:33 CST 2020
     */
    int updateByExample(@Param("record") Buyer record, @Param("example") BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated Fri May 08 12:54:33 CST 2020
     */
    int updateByPrimaryKeySelective(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbggenerated Fri May 08 12:54:33 CST 2020
     */
    int updateByPrimaryKey(Buyer record);
}