package com.shop.phone.entity;

public class PhoneTransaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoneTransaction.ordersId
     *
     * @mbggenerated Fri May 08 16:35:02 CST 2020
     */
    private Integer ordersid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoneTransaction.ordersId
     *
     * @return the value of phoneTransaction.ordersId
     *
     * @mbggenerated Fri May 08 16:35:02 CST 2020
     */
    public Integer getOrdersid() {
        return ordersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoneTransaction.ordersId
     *
     * @param ordersid the value for phoneTransaction.ordersId
     *
     * @mbggenerated Fri May 08 16:35:02 CST 2020
     */
    public void setOrdersid(Integer ordersid) {
        this.ordersid = ordersid;
    }
}