package com.example.onlineshop.entity;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.buyerId
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer buyerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.phonenum
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer phonenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.buyerId
     *
     * @return the value of address.buyerId
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getBuyerid() {
        return buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.buyerId
     *
     * @param buyerid the value for address.buyerId
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setBuyerid(Integer buyerid) {
        this.buyerid = buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address
     *
     * @return the value of address.address
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address
     *
     * @param address the value for address.address
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.phonenum
     *
     * @return the value of address.phonenum
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.phonenum
     *
     * @param phonenum the value for address.phonenum
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setPhonenum(Integer phonenum) {
        this.phonenum = phonenum;
    }
}