package com.example.onlineshop.entity;

import java.util.Date;

public class Buyer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.id
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.password
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.name
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.sex
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.birthday
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.phonenum
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.email
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.rate
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.integral
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.money
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.id
     *
     * @return the value of buyer.id
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.id
     *
     * @param id the value for buyer.id
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.password
     *
     * @return the value of buyer.password
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.password
     *
     * @param password the value for buyer.password
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setPassword(Integer password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.name
     *
     * @return the value of buyer.name
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.name
     *
     * @param name the value for buyer.name
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.sex
     *
     * @return the value of buyer.sex
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.sex
     *
     * @param sex the value for buyer.sex
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.birthday
     *
     * @return the value of buyer.birthday
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.birthday
     *
     * @param birthday the value for buyer.birthday
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.phonenum
     *
     * @return the value of buyer.phonenum
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.phonenum
     *
     * @param phonenum the value for buyer.phonenum
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setPhonenum(Integer phonenum) {
        this.phonenum = phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.email
     *
     * @return the value of buyer.email
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.email
     *
     * @param email the value for buyer.email
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.rate
     *
     * @return the value of buyer.rate
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.rate
     *
     * @param rate the value for buyer.rate
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.integral
     *
     * @return the value of buyer.integral
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.integral
     *
     * @param integral the value for buyer.integral
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.money
     *
     * @return the value of buyer.money
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.money
     *
     * @param money the value for buyer.money
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}