package com.example.onlineshop.entity;

import java.util.Date;

public class Couponwarehouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponWarehouse.id
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponWarehouse.preferentialAmount
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer preferentialamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponWarehouse.minimumConsumptionAmount
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer minimumconsumptionamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponWarehouse.deadline
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponWarehouse.sellerId
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer sellerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column couponWarehouse.count
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponWarehouse.id
     *
     * @return the value of couponWarehouse.id
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponWarehouse.id
     *
     * @param id the value for couponWarehouse.id
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponWarehouse.preferentialAmount
     *
     * @return the value of couponWarehouse.preferentialAmount
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getPreferentialamount() {
        return preferentialamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponWarehouse.preferentialAmount
     *
     * @param preferentialamount the value for couponWarehouse.preferentialAmount
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setPreferentialamount(Integer preferentialamount) {
        this.preferentialamount = preferentialamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponWarehouse.minimumConsumptionAmount
     *
     * @return the value of couponWarehouse.minimumConsumptionAmount
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getMinimumconsumptionamount() {
        return minimumconsumptionamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponWarehouse.minimumConsumptionAmount
     *
     * @param minimumconsumptionamount the value for couponWarehouse.minimumConsumptionAmount
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setMinimumconsumptionamount(Integer minimumconsumptionamount) {
        this.minimumconsumptionamount = minimumconsumptionamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponWarehouse.deadline
     *
     * @return the value of couponWarehouse.deadline
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponWarehouse.deadline
     *
     * @param deadline the value for couponWarehouse.deadline
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponWarehouse.sellerId
     *
     * @return the value of couponWarehouse.sellerId
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getSellerid() {
        return sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponWarehouse.sellerId
     *
     * @param sellerid the value for couponWarehouse.sellerId
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setSellerid(Integer sellerid) {
        this.sellerid = sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column couponWarehouse.count
     *
     * @return the value of couponWarehouse.count
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column couponWarehouse.count
     *
     * @param count the value for couponWarehouse.count
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}