package com.example.onlineshop.entity;

public class Shoppingcart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingCart.buyerId
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer buyerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingCart.goodsId
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingCart.counts
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    private Integer counts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingCart.buyerId
     *
     * @return the value of shoppingCart.buyerId
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getBuyerid() {
        return buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingCart.buyerId
     *
     * @param buyerid the value for shoppingCart.buyerId
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setBuyerid(Integer buyerid) {
        this.buyerid = buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingCart.goodsId
     *
     * @return the value of shoppingCart.goodsId
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingCart.goodsId
     *
     * @param goodsid the value for shoppingCart.goodsId
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingCart.counts
     *
     * @return the value of shoppingCart.counts
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingCart.counts
     *
     * @param counts the value for shoppingCart.counts
     *
     * @mbggenerated Sat May 02 23:38:34 CST 2020
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }
}